name: Deploy Docker Compose

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/deploy-compose.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create project directory on server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /opt/devops-lab/docker"

      - name: Copy Docker configs to server
        run: |
          scp -r docker/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/devops-lab/docker/

      - name: Deploy app stack
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /opt/devops-lab/docker/app && docker compose up -d"

      - name: Deploy Zabbix stack
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /opt/devops-lab/docker/zabbix && docker compose up -d"