name: Terraform Check

on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-check.yml"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-check.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false
        
      - name: Create dummy SSH public key
        run: echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDummyKeyForTerraformValidateOnly ci@github" > /tmp/id_ed25519.pub  

      - name: Terraform validate
        run: terraform validate